# Primeiros comandos

1) Crie um script em Python que solicite o nome, altura e peso de uma pessoa e mostre a seguinte mensagem: “João tem 90 kilos e altura de 1.78 e portanto o IMC é de 28.4”.

In [1]:
name = input("Insira o nome: ")
height = float(input("Insira a altura: "))
weight = float(input("Insira o peso: "))
imc = weight/(height * height)

print(name, " tem ", weight, " kilos e altura de ", height, " e portanto o IMC é de ", imc)

Insira o nome: João
Insira a altura: 1.78
Insira o peso: 90
João  tem  90.0  kilos e altura de  1.78  e portanto o IMC é de  28.40550435551067


2) Escreva um script que leia um valor em metros e o exiba convertido em milímetros

In [8]:
metersValue = 1.78
milimiterValue = metersValue * 1000 * 100
int(milimiterValue)

178000

3) Escreva um script que leia a quantidade de dias,horas, minutos e segundos para o usuário. Calcule o total em segundos.

In [6]:
days = int(input("Insira a quantidade de dias: "))
hours = int(input("Insira a quantidade de horas: "))
min = int(input("Insira a quantidade de minutos: "))

x_min_sec = min * 60
x_hour_min_sec = hours * 60 * 60
x_days_sec = days * 24 * 60

print("min: ", x_min_sec, "hour: ", x_hour_min_sec, "days: ", x_days_sec)

Insira a quantidade de dias: 12
Insira a quantidade de horas: 120
Insira a quantidade de minutos: 15
min:  900 hour:  432000 days:  17280


4) Faça um script que calcule o aumento de salário. Ele deve solicitar o valor do salário e a porcentagem de aumento. Exiba o valor do aumento e do novo salário.

In [7]:
sal = float(input("Salary value: "))
tax = float(input("Insira a taxa de aumento"))

sal = sal + (sal * tax/100)

print("Salário: ", sal)

Salary value: 1200
Insira a taxa de aumento10
Salário:  1320.0


5) Leia a temperatura em graus Celsius e converta para Fahrenheit.

In [10]:
C = float(input("Temperature (Celsius): "))

F = C * 1.8 + 32

print("Fahrenheit: ", F)

Temperature (Celsius): 0
Fahrenheit:  32.0


# Loops e Condicionais

1) Em química, o pH de uma solução aquosa é uma medida da sua acidez.Os Valores de pH variam entre 0 e 14. Soluções ácidas tem pH maior que 7. Soluções básicas tem pH menor que 7. Soluções neutras tem pH igual a 7. Escreva duas funções que recebem um número correspondente ao pH de uma solução aquosa e exibem na tela o tipo de solução (algo como “A solução é ácida”).

In [4]:
def wet_solution(pH):
    if(pH < 7):
        return "solução ácida"
    if(pH == 7):
        return "solução neutra"
    return "solução básica"

pH = float(input("Diga o ph da solução: ")) 
wet_solution(pH)

Diga o ph da solução10


'solução básica'

2) Em um script, o usuário deve responder à pergunta “Continuar (s/n)?”. Se o usuário digitar ‘s’ ou ‘S’, o script deve retornar a mensagem “OK, continuando...”. Se o usuário digitar ‘n’ ou ‘N’, o script deve retornar a mensagem “OK, parando...”. Por fim, se o usuário digitar qualquer outra coisa, o script deve retornar uma mensagem de erro.

In [8]:
contin = input("Continuar (s/n)? ")

contin.lower()

if(contin == 's'):
    print("Ok, continuando...")
elif(contin == 'n'):
    print("Ok, parando...")
else:
    print("Erro")

Continuar (s/n)? l
Erro


3) Faça um programa para escrever a contagem regressiva do lançamento de um foguete. O programa deve imprimir 10, 9, 8, ..., 1, 0 e Fogo! na tela

In [11]:
cont = 10
while cont != 0:
    print(cont)
    cont = cont - 1
print("Fogo!")

10
9
8
7
6
5
4
3
2
1
Fogo!


In [21]:
for i in range(10, 1, -1):
    print(i)
print("Fogo!")

10
9
8
7
6
5
4
3
2
Fogo!


4) Crie um programa que imprima a sequência de Fibonacci até o décimo termo usando um loop for.

In [20]:
fibo = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
for f in fibo:
    print(f)

1
1
2
3
5
8
13
21
34
55


5) Escreva um programa que encontre e imprima todos os números primos entre 1 e 100.

In [4]:
import math

In [12]:
divisor = 0
for i in range(2, 100):
    print(i)
    for j in range(1, 100):
        if(i % j == 0):
            divisor+=1

    if(divisor == 2):
        print("É primo")
    if(divisor != 2):
        print("É composto")
    divisor = 0

2
É primo
3
É primo
4
É composto
5
É primo
6
É composto
7
É primo
8
É composto
9
É composto
10
É composto
11
É primo
12
É composto
13
É primo
14
É composto
15
É composto
16
É composto
17
É primo
18
É composto
19
É primo
20
É composto
21
É composto
22
É composto
23
É primo
24
É composto
25
É composto
26
É composto
27
É composto
28
É composto
29
É primo
30
É composto
31
É primo
32
É composto
33
É composto
34
É composto
35
É composto
36
É composto
37
É primo
38
É composto
39
É composto
40
É composto
41
É primo
42
É composto
43
É primo
44
É composto
45
É composto
46
É composto
47
É primo
48
É composto
49
É composto
50
É composto
51
É composto
52
É composto
53
É primo
54
É composto
55
É composto
56
É composto
57
É composto
58
É composto
59
É primo
60
É composto
61
É primo
62
É composto
63
É composto
64
É composto
65
É composto
66
É composto
67
É primo
68
É composto
69
É composto
70
É composto
71
É primo
72
É composto
73
É primo
74
É composto
75
É composto
76
É composto
77
É composto
78
É co

6) Escreva um programa que determine se um número é primo ou não.

In [16]:
number = int(input("Insira um número"))
divisor = 0

for i in range(1, 100):
    if(number % i == 0):
        divisor += 1

if(divisor == 2):
    print("É primo")
else:
    print("Não é primo")

Insira um número2
É primo


7) Escreva um programa que simule um caixa eletrônico, solicitando ao usuário que insira o valor do saque e informando quantas notas de cada valor serão entregues (considere notas de R$ 100, R$ 50, R$ 20, R$ 10, R$ 5 e R$ 2).

In [23]:
saque = float(input("Insira o valor do saque: "))
value = 0

while value != saque:
    print("Insira quantas notas serão entregues:")
    hundred = int(input("R$100,00: "))
    value = hundred * 100 + value
    print("Falta R$", saque - value)
    
    fifty = int(input("R$50,00: "))
    value = fifty * 50 + value
    print("Falta R$", saque - value)
    
    twenty = int(input("R$20,00: "))
    value = twenty * 20 + value
    print("Falta R$", saque - value)
    
    ten = int(input("R$10,00: "))
    value = ten * 10 + value
    print("Falta R$", saque - value)
    
    five = int(input("R$5,00: "))
    value = five * 5 + value
    print("Falta R$", saque - value)
    
    two = int(input("R$2,00: "))
    value = two * 2 + value
    print("Falta R$", saque - value)
    

print("Dinheiro sacado!")

Insira o valor do saque: 200
Insira quantas notas serão entregues:
R$100,00: 1
Falta R$ 100.0
R$50,00: 0
Falta R$ 100.0
R$20,00: 2
Falta R$ 60.0
R$10,00: 1
Falta R$ 50.0
R$5,00: 4
Falta R$ 30.0
R$2,00: 15
Falta R$ 0.0
Dinheiro sacado!


8) Crie um programa que calcule o IMC (Índice de Massa Corporal) de uma pessoa e forneça uma classificação com base no resultado.

In [30]:
w = float(input("Insira o peso: "))
h = float(input("Insira a altura: "))
imc = w/h**2 * 10000
imc = round(imc, 1)
print(imc)
if(imc < 18.5):
    print("Magreza")
if(imc >= 18.5 and imc < 25):
    print("Normal")
if(imc >= 25 and imc <= 29.9):
    print("Sobrepeso")
if(imc >= 30 and imc <=39.9):
    print("Obesidade")
if(imc > 40):
    print("Obesidade grave")

Insira o peso: 59
Insira a altura: 171
20.2
Normal


9) Crie um programa que determine se um número é um número de Armstrong ou não. Um número de Armstrong é aquele que é igual à soma de seus dígitos elevados à potência do número de dígitos.

In [44]:
n = str(input("Digite um número: "))
l = len(n)
count = 0

for i in n:
    count += int(i)**l
    
print(count)

if(count == int(n)):
    print(count, "é um número de Armstrong!")
else:
    print("Não é um número de Armstrong!")

Digite um número: 10
1
Não é um número de Armstrong!


# Variáveis compostas - Listas

1) Faça um Programa que leia uma lista de 10 números reais e mostre-os na ordem inversa.

In [54]:
i = 0
r = []
while i < 10:
    print((i))
    r.append(float(input("Digite um número real: ")))
    i += 1

r.reverse()
print(r)

0
Digite um número real: 1
1
Digite um número real: 2
2
Digite um número real: 3
3
Digite um número real: 4
4
Digite um número real: 5
5
Digite um número real: 6
6
Digite um número real: 7
7
Digite um número real: 8
8
Digite um número real: 9
9
Digite um número real: 10
[10.0, 9.0, 8.0, 7.0, 6.0, 5.0, 4.0, 3.0, 2.0, 1.0]


2) Faça um programa que leia duas listas e que gere uma terceira com os elementos das duas primeiras.

In [59]:
l1 = ['a','b','c','d','e','f','g']
l2 = ['h','i', 'j', 'k', 'l', 'm']

l3 = l1 + l2
print(l3)
l1.extend(l2)
print(l1)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm']
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm']


3) A lista de temperaturas de Mons, na Bélgica, foi armazenada na lista T = [ -10, -8, 0, 1, 2, 5, -2, -4]. Faça um programa que imprima a menor e a maior temperatura, assim como a temperatura média.

In [5]:
import numpy as np

In [6]:
T = [ -10, -8, 0, 1, 2, 5, -2, -4]
print("Maximo: ", max(T))
print("Minimo: ", min(T))
print("Média: ", np.mean(T))

Maximo:  5
Minimo:  -10
Média:  -2.0


4. Faça um Programa que leia 20 números inteiros e armazene-os num lista. Armazene os números pares na lista PAR e os números IMPARES na lista impar. Imprima os três vetores.

In [3]:
twenty = 0
integer = []
par = []
imp = []
while twenty < 20:
    integer.append(int(input("Insira um inteiro: ")))
    if(integer[twenty] % 2 == 0):
        par.append(integer[twenty])
    if(integer[twenty] % 2 != 0):
        imp.append(integer[twenty])
    twenty += 1

print(integer)
print(par)
print(imp)

Insira um inteiro: 100
Insira um inteiro: 200
Insira um inteiro: 10
Insira um inteiro: 20
Insira um inteiro: 11
Insira um inteiro: 12
Insira um inteiro: 19
Insira um inteiro: 17
Insira um inteiro: 13
Insira um inteiro: 7
Insira um inteiro: 777
Insira um inteiro: 1
Insira um inteiro: 0
Insira um inteiro: 90
Insira um inteiro: 99
Insira um inteiro: 91
Insira um inteiro: 97
Insira um inteiro: 250
Insira um inteiro: 23
Insira um inteiro: 93
[100, 200, 10, 20, 11, 12, 19, 17, 13, 7, 777, 1, 0, 90, 99, 91, 97, 250, 23, 93]
[100, 200, 10, 20, 12, 0, 90, 250]
[11, 19, 17, 13, 7, 777, 1, 99, 91, 97, 23, 93]


5) Faça um Programa que peça as quatro notas de 5 alunos, calcule e armazene numa lista a média de cada aluno, imprima o número de alunos com média maior ou igual a 7.0

In [12]:
i = 0
l = []
m = []
while i < 5:
    l.append(int(input("Nota 1: ")))
    l.append(int(input("Nota 2: ")))
    l.append(int(input("Nota 3: ")))
    l.append(int(input("Nota 4: ")))
    m.append(np.mean(l))
    i += 1

i = 0
print(m)
while i < 5:
    if(m[i] > 7):
        print(m[i])
    i += 1

Nota 1: 1
Nota 2: 1
Nota 3: 1
Nota 4: 1
Nota 1: 10
Nota 2: 10
Nota 3: 10
Nota 4: 10
Nota 1: 101
Nota 2: 10
Nota 3: 9
Nota 4: 8
Nota 1: 1
Nota 2: 2
Nota 3: 0
Nota 4: 0
Nota 1: 0
Nota 2: 1
Nota 3: 0
Nota 4: 10
[1.0, 5.5, 14.333333333333334, 10.9375, 9.3]
14.333333333333334
10.9375
9.3


6) Escreva uma rotina que recebe uma lista de números e retorna a soma dos quadrados dos números.

In [15]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

i = 0
while i < len(l):
    l[i] = l[i] * l[i]
    i += 1
    
i = 0
s = 0
while i < len(l):
    s += l[i]
    i += 1

print(s)

385


7) Escreva uma rotina que recebe uma lista de números e retorna outra lista contendo somente os números ímpares. Utilizar list comprehension. 

Sintaxe da List Comprehension:
[Out-put Collection Condition]
[Do-this for-this-collection in-this-situation]
[x + 1 for x in range(5) if x%2 == 2]

In [1]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

imp = [x for x in l if x%2 == 1]
imp

[1, 3, 5, 7, 9]

8) Escreva uma função que recebe uma lista de strings e retorna a string mais longa.

In [5]:
l = ['oi', 'oi nerrrr', 'ei aperte esse botão', 'belezz', 'beleza']
maior = len(l[0])
ms = l[0]
for i in l:
    if(len(i) > maior):
        maior = len(i)
        ms = i
        
print(ms)

ei aperte esse botão


1)Escreva um programa que leia duas strings. Verifique se a segunda ocorre
dentro da primeira e imprima a posição de início.
1a string: AABBEFAATT
2a string: BE

In [6]:
s1 = input("Digite a primeira string: ")
s2 = input("Digite a segunda string: ")

print(s1.find(s2))

Digite a primeira string: AABBEFAATT
Digite a segunda string: BE
3


2) Escreva um programa que leia duas strings e gere uma terceira com os caracteres comuns às duas strings lidas.
1a string: AAACTBF
2a string: CBT

In [7]:
s1 = input("String 1: ")
s2 = input("String 2: ")
s3 = s1 + s2
s3

String 1: AAACTBF
String 2: CBT


'AAACTBFCBT'

3) Escreva um programa que leia uma string e imprima quantas vezes cada caractere aparece nessa string. String: TTAAC Resultado: T: 2x A: 2x C: 1x

In [10]:
s = input("Digite uma string: ")
l = []
for i in s:
    l.append(s.count(i))
    
s = set(s) # Cria um conjunto, eliminando duplicatas

for index, i in enumerate(s):
    print(i, ":", l[index])

Digite uma string: TTAAC
C : 2
T : 2
A : 2


4) Escreva um programa que leia três strings. Imprima o resultado da substituição na primeira, dos caracteres da segunda pelos da terceira. 1a string: AATTCGAA 2a string: TG 3a string: AC

In [12]:
s1 = input("String 1: ")
s2 = input("String 2: ")
s3 = input("String 3: ")

s = s1.replace(s2, s3)
print(s)

String 1: AATTCGAA
String 2: TG
String 3: AC
AATTCGAA


5) Escreva uma função em Python que receba uma string como entrada e verifique se ela é um palíndromo.

In [14]:
s = input("Digite uma string: ")
invertida = s[::-1]

if s == invertida:
    print("Palindromo")
else:
    print("Não Palindromo")

Digite uma string: oi
Não Palindromo


6) Escreva uma função em Python que receba uma string como entrada e retorne a string com cada palavra em ordem inversa.

In [15]:
s = input("Digite uma string: ")
invertida = s[::-1]
invertida

Digite uma string: oi ne


'en io'

7) Escreva um programa que receba uma string e retorne apenas as palavras que possuem mais de três caracteres.

In [18]:
s = input("Digite uma string: ")

f = s.split()

for i in f:
    if len(i) > 3:
        print(i)

Digite uma string: oi ne fia ce ta bemm
bemm


# Dictionary Exercises

1) Escreva um programa que gere um dicionário, onde cada chave seja um caractere, e seu valor seja o número desse caractere encontrado em uma frase lida. Exemplo: O rato -> { “O”:1, “r”:1, “a”:1, “t”:1, “o”:1}

In [3]:
c = 'O rato'
c = c.replace(' ', '')
l = set(c)
d = {}
for i in l:
    d[i] = c.count(i)
d

{'o': 1, 't': 1, 'a': 1, 'r': 1, 'O': 1}

2) Crie um dicionário, chamado frutas, de frutas e seus preços.
    a. Crie um segundo dicionário chamado compras na qual as
chaves são as frutas e valores é a quantidade a ser comprada
    b. Calcule o preço total de um carrinho de compras de frutas
usando o dicionário criado no exercício anterior.
    c. Remova todas as frutas do dicionário de frutas que custam
mais de R$ 5,00.

In [14]:
frutas = {'Maçã':127, 'Banana':138, 'Pera':337} # key-value = frutas-preços
frutas['Banana']

138

In [15]:
# exercicio a:
compras = {'Maçã':23, 'Banana': 12, 'Pera': 5} # key-value = frutas-quantidade
compras

{'Maçã': 23, 'Banana': 12, 'Pera': 5}

In [16]:
for i in frutas:
    Compras[i]


Maçã
Banana
Pera


3) Faça um programa que leia o nome RA e média final de uma aluno.
Armazene todas as informações num dicionário. No final programa
deve imprimir as informações do dicionário e situação do aluno
(reprovado, exame ou aprovado). Utilize as regras da UNIFESP
para definir a situação do aluno.

In [1]:
name = input("Digite o Nome: ")
ra = input("Digite o RA: ")
mF = float(input("Digite a média final: "))
d = {'Nome':name, 'RA':ra, 'Média final':mF}
print(d)

if(mF >= 6):
    print("Aprovado")
if(mF >= 3 and mF < 6):
    print("Exame")
if(mF < 3):
    print("Reprovado")

Digite o Nome: Harrison
Digite o RA: 156264
Digite a média final: 10
{'Nome': 'Harrison', 'RA': '156264', 'Média final': 10.0}
Aprovado


4) Crie um programa que leia nome, sexo, peso e altura de várias
pessoas. guarde os dados de cada pessoa num dicionário
individual e acrescente o IMC da pessoa. Organize todos os
dicionários em uma lista. No final mostre
a. Quantas pessoas foram cadastradas
b. Qual é o peso médio das pessoas
c. Qual é a altura média das pessoas
d. Qual é IMC médio das pessoas

In [3]:
l = []
n = int(input("Digite quantas pessoas: "))
i = 0

while i < n:
    name = input("Digite o nome: ")
    sex = input("Digite o sexo: ")
    weight = float(input("Digite o peso: "))
    height = int(input("Digite a altura: "))

    d = {}
    d['Nome'] = name
    d['Sexo'] = sex
    d['Peso'] = weight
    d['Altura'] = height
    l.append(d)
    i += 1

print(l)
print("Quantidade de cadastrados: ", len(l))

weight = 0
for i in l:
    weight += i['Peso']
    
print("Peso médio das pessoas: ", weight/len(l))

height = 0
for i in l:
    height += i['Altura']
    
print("Altura média das pessoas: ", height/len(l))

Digite quantas pessoas: 2
Digite o nome: H
Digite o sexo: k
Digite o peso: 10
Digite a altura: 10
Digite o nome: oi
Digite o sexo: ne
Digite o peso: 20
Digite a altura: 30
[{'Nome': 'H', 'Sexo': 'k', 'Peso': 10.0, 'Altura': 10}, {'Nome': 'oi', 'Sexo': 'ne', 'Peso': 20.0, 'Altura': 30}]
Quantidade de cadastrados:  2
Peso médio das pessoas:  15.0
Altura média das pessoas:  20.0


5) Escreva um programa para agrupar uma lista de dicionários por
uma chave específica

6) Escreva um programa para verificar se uma chave específica existe
no dicionário ou não.

In [13]:
d = {'Nome':name, 'RA':ra, 'Média final':mF}
s = input("Digite a chave: ")
n = 0
for i in d:
    if i == s:
        print("Está na lista")
    else:
        n += 1
        
if n == len(d):
    print("Não está na lista")

Digite a chave: Média final
Está na lista


7) Escreva um programa para criar um set de todos os caracteres
únicos em uma string.

In [32]:
s = input("Digite uma frase: ")

for i in s:
    if s.count(i) > 1:
        removable = s.count(i)
        j = 0
        while j < removable:
            s = s.replace(i, ' ')
            s = s.replace(' ', '')
            j += 1
            
s = set(s)
print(s)

Digite uma frase: oi tudo bem com voce
{'t', 'u', 'b', 'v', 'i', 'd'}


8) Crie um programa que gerencia o aproveitamento de um jogador
de futebol. o programa vai ler o nome do jogador e quantas
partidas ele jogou. Depois vai ler a quantidade de gols feitos em
cada partida. No final, tudo isso será guardado em um dicionário
incluindo o total de gols realizados durante o campeonato

## Numpy

In [1]:
import numpy as np

1. Crie um array unidimensional com valores aleatórios e imprima o valor médio e a mediana.

In [10]:
l = np.random.randint(1, 10, (1, 10))
print(l)
print(l.mean())
# mediana ordena o array e faz a media dos dois do meio se for par
print(np.median(l))

[[7 9 4 3 8 8 8 1 2 5]]
5.5
6.0


2- Crie um array unidimensional com valores aleatórios e inverta a
ordem dos elementos.

In [15]:
l = np.random.randint(1,10, (1,10))
print(l)
np.flip(l)

[[8 5 5 5 7 6 8 4 8 7]]


array([[7, 8, 4, 8, 6, 7, 5, 5, 5, 8]])

3- Crie um array unidimensional com valores aleatórios e calcule a
diferença entre cada elemento e o próximo elemento.

In [39]:
l = np.random.randint(1,10, (1,10))
a = []
print(l)
for j in range(0, 10):
    if(j < 10 - 1):
        a.append(l[0][j] - l[0][j + 1])
    if j == 9:
        a.append(l[0][9])
a

[[2 2 2 2 7 5 3 5 6 9]]


[0, 0, 0, -5, 2, 2, -2, -1, -3, 9]

4- Crie uma matriz de zeros de tamanho 10x10 e adicione uma borda de
valor 1.

In [33]:
l = np.zeros([10,10])
l

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

5- Crie um array unidimensional com valores aleatórios e encontre o
índice do valor mais próximo de um valor fornecido

In [44]:
forn = int(input("Digite um valor de 0 a 10 para aproximar: "))
l = 10 * np.random.rand(1, 10)
achieved = 0
min_n = l[0][0]
max_n = l[0][0]

for j in range(0, 10):
    if round(l[0][j]) == forn:
        achieved = 1
        
    if min_n > l[0][0]:
        
    if max_n > l[0][0]:
        
    if min_n - max_n >= 0:
        
    if min_n - max_n < 0:
    
    if achieved == 1:
        break;

print(l)
print(j)
    

Digite um valor de 0 a 10 para aproximar: 5
[[7.94378071 5.61879902 8.40167575 8.66866927 7.18676721 8.97402363
  3.49639435 7.30193671 5.77198265 9.75744672]]
9


6- Crie um array unidimensional com valores aleatórios e encontre os
valores únicos e suas contagens.